# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d8726b56081313c90ef40fde43eaf372e061cb26321ee1dce84f6af682e8c10e58552702134e8c55747f3ecc843d99a41ecf6c48a93fe1b1ade0c779e53afad

test:
  secret_key_base: fd9621f7c2d875e204b39d8e441dc1b4b5b74a43865595dd81f87fc8d0a775fa3ab9f772068bc260a0fa2da6b9137725052f0322b0b9931106d88a19b9408f8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
